/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Snooze (https://sketchfab.com/Snooze)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-sci-fi-tablet-ee1fde7ec1514fd5a61790809ebd46a6
title: Low Poly Sci-Fi Tablet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { goTo } from '../../utils/navigation'
import TextCustom from './TextCustom';

export default function Tablet({position, rotation, scale}) {
  const { nodes, materials } = useGLTF('assets/tablet/tablet-transformed.glb')
  const [isHovered, setIsHovered] = React.useState(false);
  const [cameraRotation, setCameraRotation] = React.useState([0, 0, 0]);

  function handleTabletClick(){
    goTo('contact');
  }

  return (
    <>
    <group position={position}  rotation={rotation} dispose={null} scale={scale} 
    onClick={() => handleTabletClick()}
    onPointerEnter={(e ) => {
      setIsHovered(true),
      setCameraRotation(e.camera.rotation)
    }}
    onPointerLeave={() => setIsHovered(false)}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial.geometry} material={materials.MAT_TabletGlass} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_1.geometry} material={materials.MAT_OpacityText} />
          <mesh castShadow receiveShadow geometry={nodes.defaultMaterial_2.geometry} material={materials.MAT_Tablet} />
        </group>
      </group>
    </group>
    {isHovered ? <TextCustom message={"Me contacter"} position={[position[0] - 150, position[1] + 200, position[2]]} color={"#ffffff"} size={20} rotation={cameraRotation} bevelThickness={.5} /> : null }
    </>
  )
}

useGLTF.preload('assets/tablet/tablet-transformed.glb')
